Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,5 @@
 name: Odoo Testing
+
 on:
   push:
     branches:
@@ -6,12 +7,15 @@ on:
   pull_request:
     branches:
       - main
+
 jobs:
   test:
     runs-on: ubuntu-latest
+
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
+
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
@@ -22,10 +26,6 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y postgresql postgresql-contrib
         sudo service postgresql start
-      run: sudo apt-get install -y postgresql postgresql-contrib
-
-    - name: Start PostgreSQL service
-      run: sudo service postgresql start
 
     - name: Install system dependencies
       run: |
@@ -36,24 +36,31 @@ jobs:
         xfonts-75dpi gdebi node-less libffi-dev npm
         if [ ! -e /usr/bin/node ]; then sudo ln -s /usr/bin/nodejs /usr/bin/node; fi
         sudo npm install -g less less-plugin-clean-css rtlcss
+
     - name: Upgrade pip
       run: python -m pip install --upgrade pip
+
     - name: Install setuptools==58.0.4
       run: pip install setuptools==58.0.4
+
     - name: Install Python dependencies
-      run: pip install -r requirements.txt
+      run: |
+        if [ ! -f requirements.txt ]; then echo "requirements.txt not found"; exit 1; fi
+        pip install -r requirements.txt
+
     - name: Install Odoo
       run: |
         wget https://nightly.odoo.com/16.0/nightly/src/odoo_16.0.latest.tar.gz
         tar -xf odoo_16.0.latest.tar.gz
         mv odoo-16.0* odoo
         pip install -r odoo/requirements.txt
+
     - name: Create PostgreSQL user and database
       run: |
         sudo -u postgres createuser -s odoo
         sudo -u postgres createdb -O odoo theodooguys
         sudo -u postgres psql -c "ALTER USER odoo WITH PASSWORD 'odoo';"
+
     - name: Run tests
       run: |
-        python3 V16.0/odoo/odoo-bin -c .odoorc -d theodooguys --test-enable --stop-after-init -u real_estate_ads
-     
+        python3 odoo/odoo-bin -c .odoorc -d theodooguys --test-enable --stop-after-init -u real_estate_ads
